{{- if .Values.enableRBAC -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "strongswan.fullname" . }}
  namespace: {{ template "strongswan.namespace" . }}
  labels:
    app: {{ template "strongswan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "strongswan.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "strongswan.fullname" . }}
  namespace: {{ template "strongswan.namespace" . }}
{{- end -}}
