apiVersion: v1
description: A strongSwan IPSec VPN service to securely connect your Kubernetes cluster to another network.
name: strongswan
home: https://www.strongswan.org/
icon: https://www.strongswan.org/images/strongswan.png
keywords:
- strongswan
- ipsec
- vpn
- tunnel
- Network
- amd64
- IKS
- Limited
maintainers:
- name: John Kasperski
  email: jckasper@us.ibm.com
appVersion: 25.08.20
version: 2.10.7
